# Generated by Django 6.0.4 on 2026-05-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandevisite',
            name='date_reponse',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandevisite',
            name='reponse_proprietaire',
            field=models.TextField(blank=True, null=True),
        ),
    ]
