services:
  - type: web
    name: logement-immobilier
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: RENDER_EXTERNAL_HOSTNAME
        fromService:
          type: web
          name: logement-immobilier
          property: host
