# Generated by Django 6.0.5 on 2026-05-11 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalementAnnonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison', models.CharField(choices=[('fausse', 'Fausse annonce'), ('prix_suspect', 'Prix suspect'), ('photos_trompeuses', 'Photos trompeuses'), ('deja_louee', 'Annonce déjà louée'), ('contenu_incorrect', 'Contenu incorrect'), ('autre', 'Autre')], max_length=50)),
                ('message', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('traite', 'Traité'), ('ignore', 'Ignoré')], default='nouveau', max_length=20)),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='properties.annonce')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements_annonces', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
